[tools]
ninja = "1.13.2"
cmake = "4.2.1"
python = ["3.10", "3.14.2"]
ripgrep = "15.1.0"
fd = "10.3.0"
"github:llvm/llvm-project" = "llvmorg-21.1.8"
"github:neocmakelsp/neocmakelsp" = "v0.9.1"
# NOTE: your gpg --version -> 2.+ expected by 'mise'
node = "24.13.0"
npm = "11.8.0"
shfmt = "3.12.0"
# be advisedhttps://mise.jdx.dev/dev-tools/backends/github.html:
# lldb: error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory
# so I just copy this so from python3.10 installation into llvm installation inside mise
[env]
LD_LIBRARY_PATH = "{{env.HOME}}/.local/share/mise/installs/github-llvm-llvm-project/llvmorg-21.1.8/lib/x86_64-unknown-linux-gnu/:{{env.LD_LIBRARY_PATH}}"
